### ISSUE TITLE
ImportError: cannot import name 'template_generic' from 'pyqtgraph.console' 

### ISSUE THREAD

**Issue by GrimPixel** [nodedge/nodedge#197]
Traceback (most recent call last):
  File "/home/user/.local/bin/nodedge", line 5, in <module>
    from nodedge.__main__ import main
  File "/home/user/.local/lib/python3.10/site-packages/nodedge/__main__.py", line 14, in <module>
    from nodedge.nodedge_app_window import NodedgeAppWindow
  File "/home/user/.local/lib/python3.10/site-packages/nodedge/nodedge_app_window.py", line 11, in <module>
    from nodedge.mdi_window import MdiWindow
  File "/home/user/.local/lib/python3.10/site-packages/nodedge/mdi_window.py", line 21, in <module>
    from nodedge.console_widget import ConsoleWidget
  File "/home/user/.local/lib/python3.10/site-packages/nodedge/console_widget.py", line 8, in <module>
    from pyqtgraph.console import template_generic as ui_template
ImportError: cannot import name 'template_generic' from 'pyqtgraph.console' (/home/user/.local/lib/python3.10/site-packages/pyqtgraph/console/__init__.py)

**Comment by Gjacquenot** [comment]
I got the same error on Windows with Python 3.8 

```
python -m pip install nodedge
Collecting nodedge
  Downloading nodedge-0.5.0-py3-none-any.whl (224 kB)
     ---------------------------------------- 224.1/224.1 kB 2.7 MB/s eta 0:00:00

Successfully installed PySide6-Essentials-6.3.1 asammdf-7.3.14 canmatrix-1.0 coloredlogs-15.0.1 humanfriendly-10.0 isal-1.2.0 lz4-4.3.2 nodedge-0.5.0 pyqtconsole-1.2.2 pyqtgraph-0.13.3 pyreadline3-3.4.1 shiboken6-6.3.1 types-PyYAML-6.0.12.11


nodedge
===== 2023.08.16 14:08:06 =====
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\nodedge.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python38\lib\site-packages\nodedge\__main__.py", line 14, in <module>
    from nodedge.nodedge_app_window import NodedgeAppWindow
  File "C:\Program Files\Python38\lib\site-packages\nodedge\nodedge_app_window.py", line 11, in <module>
    from nodedge.mdi_window import MdiWindow
  File "C:\Program Files\Python38\lib\site-packages\nodedge\mdi_window.py", line 21, in <module>
    from nodedge.console_widget import ConsoleWidget
  File "C:\Program Files\Python38\lib\site-packages\nodedge\console_widget.py", line 8, in <module>
    from pyqtgraph.console import template_generic as ui_template
ImportError: cannot import name 'template_generic' from 'pyqtgraph.console' (C:\Program Files\Python38\lib\site-packages\pyqtgraph\console\__init__.py)
```

**Comment by Gjacquenot** [comment]
The installed wheel from pypi downloads the latest dependencies for `nodedge`. It means that `pyqtgraph` is installed with version 0.13.3, whereas [frozen version](https://github.com/nodedge/nodedge/blob/373fae838cd31df5d56940d80d386fbb09227007/requirements/freeze/requirements.txt) uses 0.13.1.

I guess one should stick with the frozen version. We can do with a `pip install -r requirements.txt` before installing `nodedge`

**Comment by nodedge** [comment]
Hello Guillaume, 

Thank you for your message.
I am updating the project right now: #204 

The console is now integrated into `pyqtgraph`, so we don't need our own console widget in Nodedge.
